apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: scg-apply-prod

patchesStrategicMerge:
- ingress.yaml
- deployment.yaml
- service.yaml

resources:
- ../../../base/be
- namespace.yaml
- secret.yaml
images:
- name: scgskku/scg-apply-be-prod
  newTag: 6ef0bdab1437936dcf795cbeb5bfa950d485b2f9
