apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: scg-apply-prod

patchesStrategicMerge:
- ingress.yaml
- deployment.yaml
- service.yaml

resources:
- ../../../base/be
- namespace.yaml
- secret.yaml
images:
- name: scgskku/scg-apply-be-prod
  newTag: f7fcb7d9930357450815ca6e8c87b015edff5af7
