apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: scg-apply-prod

patchesStrategicMerge:
- ingress.yaml
- deployment.yaml
- service.yaml

resources:
- ../../../base/be
- namespace.yaml
- secret.yaml
images:
- name: scgskku/scg-apply-be-prod
  newTag: cb7c68244f0a737649546510b39fe67a87d6ffb8
