apiVersion: v1
kind: Secret
metadata:
  name: scg-apply-secret
type: Opaque
data:
  APP_ENV: <path:kv/data/scg-apply-secret#app-env | base64encode>
  APP_PORT: <path:kv/data/scg-apply-secret#app-port | base64encode>
  JWT_SECRET: <path:kv/data/scg-apply-secret#jwt-secret | base64encode>
  DATABASE_URL: <path:kv/data/scg-apply-secret#db-url | base64encode>
  MINIO_END_POINT: <path:kv/data/scg-apply-secret#minio-endpoint | base64encode>
  MINIO_PORT: <path:kv/data/scg-apply-secret#minio-port | base64encode>
  MINIO_ACCESS_KEY: <path:kv/data/scg-apply-secret#minio-user | base64encode>
  MINIO_SECRET_KEY: <path:kv/data/scg-apply-secret#minio-secret | base64encode>
  MINIO_BUCKET_NAME: <path:kv/data/scg-apply-secret#minio-bucket | base64encode>
