apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: scg-apply-dev
namePrefix: dev-
patchesStrategicMerge:
  - ingress.yaml
  - deployment.yaml
  - service.yaml
resources:
  - ../../../base/be
images:
  - name: registry.scg.skku.ac.kr/scg-apply-backend
    newTag: dev0
