apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: scg-apply-prod
namePrefix: prod-
patchesStrategicMerge:
- ingress.yaml
- deployment.yaml
- service.yaml
resources:
- ../../../base/fe
images:
- name: scgskku/scg-apply-fe-prod
  newTag: 87edfa18e401cdce8c987ad0acb1f550486d0c70
