apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: scg-apply-prod
namePrefix: prod-
patchesStrategicMerge:
- ingress.yaml
- deployment.yaml
- service.yaml
resources:
- ../../../base/fe
images:
- name: scgskku/scg-apply-fe-prod
  newTag: e741fb4cd85c251375922acf8120c76abf72b768
