apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: scg-apply-prod
namePrefix: prod-
patchesStrategicMerge:
- ingress.yaml
- deployment.yaml
- service.yaml
resources:
- ../../../base/fe
images:
- name: scgskku/scg-apply-fe-prod
  newTag: c92d3159d698fff8893bfb31efb47c3f4539fcee
